version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Front-End Deploy App
          command: |
            npm run frontend:deploy
      # Installing AWS Elastic Beanstalk CLI
      - run:
          name: Installing AWS Elasticbeanstalk
          command: |
            npm run backend:aws-eb
      # Deploying the backend to AWS Elastic Beanstalk
      - run:
          name: Back-End Deploy
          command: |
            npm run backend:deploy
workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
          context: aws
          filters:
            branches:
              only:
                - main
